[book]
title = "BamOS Documentation"
authors = ["Konstantin Pigulevskiy @bagggage"]
src = "src"
language = "en"
text-direction = "ltr"

[preprocessor.alerts]


[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "dark"
copy-fonts = false

[output.html.print]
enable = true
page-break = true
